# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mecab.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mecab.proto',
  package='mecab',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmecab.proto\x12\x05mecab\"5\n\x0cParseRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\x12\x12\n\ndictionary\x18\x02 \x01(\t\"3\n\rParseResponse\x12\"\n\tsentences\x18\x01 \x03(\x0b\x32\x0f.mecab.Sentence\"&\n\x08Sentence\x12\x1a\n\x05words\x18\x01 \x03(\x0b\x32\x0b.mecab.Word\"(\n\x04Word\x12\x0f\n\x07surface\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x65\x61ture\x18\x02 \x03(\t2=\n\x05MeCab\x12\x34\n\x05Parse\x12\x13.mecab.ParseRequest\x1a\x14.mecab.ParseResponse\"\x00\x62\x06proto3')
)




_PARSEREQUEST = _descriptor.Descriptor(
  name='ParseRequest',
  full_name='mecab.ParseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='mecab.ParseRequest.sentences', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dictionary', full_name='mecab.ParseRequest.dictionary', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_PARSERESPONSE = _descriptor.Descriptor(
  name='ParseResponse',
  full_name='mecab.ParseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentences', full_name='mecab.ParseResponse.sentences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=128,
)


_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='mecab.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='mecab.Sentence.words', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=168,
)


_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='mecab.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='surface', full_name='mecab.Word.surface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='mecab.Word.feature', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=210,
)

_PARSERESPONSE.fields_by_name['sentences'].message_type = _SENTENCE
_SENTENCE.fields_by_name['words'].message_type = _WORD
DESCRIPTOR.message_types_by_name['ParseRequest'] = _PARSEREQUEST
DESCRIPTOR.message_types_by_name['ParseResponse'] = _PARSERESPONSE
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['Word'] = _WORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseRequest = _reflection.GeneratedProtocolMessageType('ParseRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARSEREQUEST,
  __module__ = 'mecab_pb2'
  # @@protoc_insertion_point(class_scope:mecab.ParseRequest)
  ))
_sym_db.RegisterMessage(ParseRequest)

ParseResponse = _reflection.GeneratedProtocolMessageType('ParseResponse', (_message.Message,), dict(
  DESCRIPTOR = _PARSERESPONSE,
  __module__ = 'mecab_pb2'
  # @@protoc_insertion_point(class_scope:mecab.ParseResponse)
  ))
_sym_db.RegisterMessage(ParseResponse)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'mecab_pb2'
  # @@protoc_insertion_point(class_scope:mecab.Sentence)
  ))
_sym_db.RegisterMessage(Sentence)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), dict(
  DESCRIPTOR = _WORD,
  __module__ = 'mecab_pb2'
  # @@protoc_insertion_point(class_scope:mecab.Word)
  ))
_sym_db.RegisterMessage(Word)



_MECAB = _descriptor.ServiceDescriptor(
  name='MeCab',
  full_name='mecab.MeCab',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=212,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='Parse',
    full_name='mecab.MeCab.Parse',
    index=0,
    containing_service=None,
    input_type=_PARSEREQUEST,
    output_type=_PARSERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MECAB)

DESCRIPTOR.services_by_name['MeCab'] = _MECAB

# @@protoc_insertion_point(module_scope)
