# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mecab_pb2 as mecab__pb2


class MeCabStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Parse = channel.unary_unary(
        '/mecab.MeCab/Parse',
        request_serializer=mecab__pb2.ParseRequest.SerializeToString,
        response_deserializer=mecab__pb2.ParseResponse.FromString,
        )


class MeCabServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Parse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MeCabServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Parse': grpc.unary_unary_rpc_method_handler(
          servicer.Parse,
          request_deserializer=mecab__pb2.ParseRequest.FromString,
          response_serializer=mecab__pb2.ParseResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mecab.MeCab', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
